{
  config,
  lib,
  wlib,
  pkgs,
  ...
}:
{
  imports = [ wlib.modules.default ];
  options = {
    yuck = lib.mkOption {
      type = lib.types.lines;
      default = "";
    };
    style = lib.mkOption {
      type = lib.types.lines;
      default = "";
    };
    styleFormat = lib.mkOption {
      type = lib.types.enum [
        "css"
        "scss"
      ];
      default = "scss";
    };

    generatedConfig.output = lib.mkOption {
      type = lib.types.str;
      default = config.outputName;
      description = ''
        The derivation output for the config generated by this wrapper module
      '';
    };
    generatedConfig.placeholder = lib.mkOption {
      type = lib.types.str;
      default = "${placeholder config.generatedConfig.output}/${config.binName}-config";
      readOnly = true;
      description = ''
        The placeholder accessible in the wrapper derivation build script for the config generated by this wrapper module
      '';
    };
  };

  config = {
    package = lib.mkDefault pkgs.eww;

    constructFiles.yuck = {
      content = config.yuck;
      output = config.generatedConfig.output;
      relPath = "${config.binName}-config/eww.yuck";
    };

    constructFiles.style = {
      content = config.style;
      output = config.generatedConfig.output;
      relPath = "${config.binName}-config/eww.${config.styleFormat}";
    };

    flags."--config" = config.generatedConfig.placeholder;

    passthru.generatedConfig = "${
      config.wrapper.${config.generatedConfig.output}
    }/${config.binName}-config";

    meta.maintainers = [ wlib.maintainers.clay53 ];
  };
}
